### ISSUE TITLE
Itent携带的数据丢失

### ISSUE THREAD

**Issue by GitJLiu** [TxcA/ManageStartActivity#3]
按照楼主提供的继承方式使用，发现在使用starforResout时，Itent携带的数据丢失。而使用案例跳转没出现。不清楚啥情况。怎么排查呢

**Comment by TxcA** [comment]
你是第二个页面没接收到值，还是第一个页面没接收到返回值？
最好贴一下你的start调用处和setResult返回处的代码。

**Comment by GitJLiu** [comment]
第二页没有接收到值：0
第一页代码：
UploadImageActivity::class.startForResult({
                    putExtra(Constants.IS_EDIT, false)
                    putExtra(Constants.TYPE, "order")
                    putExtra(Constants.DATA, bean)
                }) { _, _ ->
                    DialogUtil.showInputMessage(
                        this, "完成原因", null,
                        positiveAction = { text ->
                            mViewModel.auditOrder(bean.orderid, "完成", text)
                        }, neutralText = null
                    )
                }
第二页接收代码：
override fun initView(savedInstanceState: Bundle?) {
        val edit = intent.getBooleanExtra(Constants.IS_EDIT, true)
    }

**Comment by TxcA** [comment]
是否初始化？
 
除了需要实现，Base类还需要调用`initManageStartActivity()`。

你看下首页README

**Comment by GitJLiu** [comment]
BaseActivity 类中有初始化的

**Comment by TxcA** [comment]
对了，你说的未接受到值0，是IS_EDIT、TYPE、DATA？
方便的话给一个sample或者clone仓库复现下。
因为Msa的使用方法很简单，继承、委托、init三步，目前看你都已经做了。

**Comment by GitJLiu** [comment]
Activity跳转后，intent内部bundle数据为为空。由于是生产代码，所以不方便提供clone.我自己在楼主的Demo上加了个一样方式的跳转也没有复现。所以有些疑惑。
1.添加依赖  2.base类init  3.参考样类调用

**Comment by TxcA** [comment]
如果确定传参正常，初始化正常的话。
你用的v7还是androidX? 当前androidX的版本是多少呢？

由于`registerForActivityResult`基于`appcompat:appcompat`或`appcompat:activity`，MSA只是对使用进行了封装。
```
    // need androidx appcompat
    implementation 'androidx.appcompat:appcompat:1.3.1'

```
如果生产代码不方便提供的话，最好有一个能复现问题的sample小样，一个空工程 + 传递后丢失的样例代码，这边才好检查问题。

**Comment by GitJLiu** [comment]
AndroidX的版本是1.2.0的，但升级到1.3.1也是有问题。看上班后能否弄一个复现的样例出来波

**Comment by GitJLiu** [comment]
问题已经找到，是intent携带的bean类数据有误，导致gson无法解析。在第二个页面取值时，影响了bundle内部的数据而导致无法取到值
